// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: cav.proto

package proto_cav

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ROS robot meta information message
type ROSMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotID   int64                `protobuf:"varint,1,opt,name=robotID,proto3" json:"robotID,omitempty"`
	RobotName string               `protobuf:"bytes,2,opt,name=robotName,proto3" json:"robotName,omitempty"`
	Origin    *Point               `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	FrameID   string               `protobuf:"bytes,4,opt,name=frameID,proto3" json:"frameID,omitempty"`
	Ts        *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *ROSMeta) Reset() {
	*x = ROSMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ROSMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROSMeta) ProtoMessage() {}

func (x *ROSMeta) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROSMeta.ProtoReflect.Descriptor instead.
func (*ROSMeta) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{0}
}

func (x *ROSMeta) GetRobotID() int64 {
	if x != nil {
		return x.RobotID
	}
	return 0
}

func (x *ROSMeta) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

func (x *ROSMeta) GetOrigin() *Point {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *ROSMeta) GetFrameID() string {
	if x != nil {
		return x.FrameID
	}
	return ""
}

func (x *ROSMeta) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type RobotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ros         *ROSMeta             `protobuf:"bytes,1,opt,name=ros,proto3" json:"ros,omitempty"`
	Velocity    float32              `protobuf:"fixed32,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	RotVelocity float32              `protobuf:"fixed32,3,opt,name=rotVelocity,proto3" json:"rotVelocity,omitempty"`
	Radius      float32              `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Ts          *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *RobotInfo) Reset() {
	*x = RobotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInfo) ProtoMessage() {}

func (x *RobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInfo.ProtoReflect.Descriptor instead.
func (*RobotInfo) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{1}
}

func (x *RobotInfo) GetRos() *ROSMeta {
	if x != nil {
		return x.Ros
	}
	return nil
}

func (x *RobotInfo) GetVelocity() float32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *RobotInfo) GetRotVelocity() float32 {
	if x != nil {
		return x.RotVelocity
	}
	return 0
}

func (x *RobotInfo) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *RobotInfo) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ros         *ROSMeta             `protobuf:"bytes,1,opt,name=ros,proto3" json:"ros,omitempty"`
	Position    *Point               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"` //position
	Orientation *Orientation         `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Ts          *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{2}
}

func (x *Position) GetRos() *ROSMeta {
	if x != nil {
		return x.Ros
	}
	return nil
}

func (x *Position) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Position) GetOrientation() *Orientation {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *Position) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// destination request message
type PathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId int64                `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	Seq     int64                `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`        //sequence number
	Radius  float32              `protobuf:"fixed32,3,opt,name=radius,proto3" json:"radius,omitempty"` //vehicle radius
	Start   *Point               `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`     //current position
	Goal    *Point               `protobuf:"bytes,6,opt,name=goal,proto3" json:"goal,omitempty"`       //desitination position
	Objects []*Point             `protobuf:"bytes,7,rep,name=objects,proto3" json:"objects,omitempty"` //additional object (like other robots)
	Ts      *timestamp.Timestamp `protobuf:"bytes,8,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{3}
}

func (x *PathRequest) GetRobotId() int64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *PathRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PathRequest) GetRadius() float32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *PathRequest) GetStart() *Point {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *PathRequest) GetGoal() *Point {
	if x != nil {
		return x.Goal
	}
	return nil
}

func (x *PathRequest) GetObjects() []*Point {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *PathRequest) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// path message
type Path struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId int64        `protobuf:"varint,1,opt,name=robotId,proto3" json:"robotId,omitempty"`
	Seq     int64        `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Path    []*PathPoint `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"` //path
}

func (x *Path) Reset() {
	*x = Path{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{4}
}

func (x *Path) GetRobotId() int64 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *Path) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Path) GetPath() []*PathPoint {
	if x != nil {
		return x.Path
	}
	return nil
}

// each point message in a path
type PathPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq         int64                `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Pose        *Point               `protobuf:"bytes,2,opt,name=pose,proto3" json:"pose,omitempty"`
	Orientation *Orientation         `protobuf:"bytes,3,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Ts          *timestamp.Timestamp `protobuf:"bytes,8,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *PathPoint) Reset() {
	*x = PathPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathPoint) ProtoMessage() {}

func (x *PathPoint) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathPoint.ProtoReflect.Descriptor instead.
func (*PathPoint) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{5}
}

func (x *PathPoint) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PathPoint) GetPose() *Point {
	if x != nil {
		return x.Pose
	}
	return nil
}

func (x *PathPoint) GetOrientation() *Orientation {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *PathPoint) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

// map meta information message
type MapMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq        int64    `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Origin     *Point   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Height     int64    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width      int64    `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Resolusion float32  `protobuf:"fixed32,5,opt,name=resolusion,proto3" json:"resolusion,omitempty"`
	Objects    []*Point `protobuf:"bytes,6,rep,name=objects,proto3" json:"objects,omitempty"` //object list in tha map
}

func (x *MapMeta) Reset() {
	*x = MapMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMeta) ProtoMessage() {}

func (x *MapMeta) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMeta.ProtoReflect.Descriptor instead.
func (*MapMeta) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{6}
}

func (x *MapMeta) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *MapMeta) GetOrigin() *Point {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *MapMeta) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapMeta) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapMeta) GetResolusion() float32 {
	if x != nil {
		return x.Resolusion
	}
	return 0
}

func (x *MapMeta) GetObjects() []*Point {
	if x != nil {
		return x.Objects
	}
	return nil
}

// point message
type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{7}
}

func (x *Point) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Orientation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W float32 `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
}

func (x *Orientation) Reset() {
	*x = Orientation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cav_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Orientation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orientation) ProtoMessage() {}

func (x *Orientation) ProtoReflect() protoreflect.Message {
	mi := &file_cav_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orientation.ProtoReflect.Descriptor instead.
func (*Orientation) Descriptor() ([]byte, []int) {
	return file_cav_proto_rawDescGZIP(), []int{8}
}

func (x *Orientation) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Orientation) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Orientation) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Orientation) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

var File_cav_proto protoreflect.FileDescriptor

var file_cav_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x61, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb1, 0x01, 0x0a, 0x07, 0x52, 0x4f, 0x53, 0x4d,
	0x65, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a,
	0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12,
	0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x09,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x03, 0x72, 0x6f, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63,
	0x61, 0x76, 0x2e, 0x52, 0x4f, 0x53, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x03, 0x72, 0x6f, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x6f, 0x74, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x0b, 0x72, 0x6f, 0x74, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72,
	0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74,
	0x73, 0x22, 0xc4, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x03, 0x72, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x52, 0x4f, 0x53, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x03, 0x72, 0x6f, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63,
	0x61, 0x76, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x63, 0x61, 0x76, 0x2e, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x22, 0xf7, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x73, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x07, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02,
	0x74, 0x73, 0x22, 0x5c, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76,
	0x2e, 0x50, 0x61, 0x74, 0x68, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x22, 0xa9, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x74, 0x68, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71,
	0x12, 0x24, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x04, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x22, 0xbf, 0x01, 0x0a,
	0x07, 0x4d, 0x61, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x22, 0x31,
	0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x7a, 0x22, 0x45, 0x0a, 0x0b, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x77, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6e, 0x65, 0x72, 0x65, 0x78, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x61, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cav_proto_rawDescOnce sync.Once
	file_cav_proto_rawDescData = file_cav_proto_rawDesc
)

func file_cav_proto_rawDescGZIP() []byte {
	file_cav_proto_rawDescOnce.Do(func() {
		file_cav_proto_rawDescData = protoimpl.X.CompressGZIP(file_cav_proto_rawDescData)
	})
	return file_cav_proto_rawDescData
}

var file_cav_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cav_proto_goTypes = []interface{}{
	(*ROSMeta)(nil),             // 0: proto_cav.ROSMeta
	(*RobotInfo)(nil),           // 1: proto_cav.RobotInfo
	(*Position)(nil),            // 2: proto_cav.Position
	(*PathRequest)(nil),         // 3: proto_cav.PathRequest
	(*Path)(nil),                // 4: proto_cav.Path
	(*PathPoint)(nil),           // 5: proto_cav.PathPoint
	(*MapMeta)(nil),             // 6: proto_cav.MapMeta
	(*Point)(nil),               // 7: proto_cav.Point
	(*Orientation)(nil),         // 8: proto_cav.Orientation
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_cav_proto_depIdxs = []int32{
	7,  // 0: proto_cav.ROSMeta.origin:type_name -> proto_cav.Point
	9,  // 1: proto_cav.ROSMeta.ts:type_name -> google.protobuf.Timestamp
	0,  // 2: proto_cav.RobotInfo.ros:type_name -> proto_cav.ROSMeta
	9,  // 3: proto_cav.RobotInfo.ts:type_name -> google.protobuf.Timestamp
	0,  // 4: proto_cav.Position.ros:type_name -> proto_cav.ROSMeta
	7,  // 5: proto_cav.Position.position:type_name -> proto_cav.Point
	8,  // 6: proto_cav.Position.orientation:type_name -> proto_cav.Orientation
	9,  // 7: proto_cav.Position.ts:type_name -> google.protobuf.Timestamp
	7,  // 8: proto_cav.PathRequest.start:type_name -> proto_cav.Point
	7,  // 9: proto_cav.PathRequest.goal:type_name -> proto_cav.Point
	7,  // 10: proto_cav.PathRequest.objects:type_name -> proto_cav.Point
	9,  // 11: proto_cav.PathRequest.ts:type_name -> google.protobuf.Timestamp
	5,  // 12: proto_cav.Path.path:type_name -> proto_cav.PathPoint
	7,  // 13: proto_cav.PathPoint.pose:type_name -> proto_cav.Point
	8,  // 14: proto_cav.PathPoint.orientation:type_name -> proto_cav.Orientation
	9,  // 15: proto_cav.PathPoint.ts:type_name -> google.protobuf.Timestamp
	7,  // 16: proto_cav.MapMeta.origin:type_name -> proto_cav.Point
	7,  // 17: proto_cav.MapMeta.objects:type_name -> proto_cav.Point
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_cav_proto_init() }
func file_cav_proto_init() {
	if File_cav_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cav_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ROSMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RobotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Path); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cav_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Orientation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cav_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cav_proto_goTypes,
		DependencyIndexes: file_cav_proto_depIdxs,
		MessageInfos:      file_cav_proto_msgTypes,
	}.Build()
	File_cav_proto = out.File
	file_cav_proto_rawDesc = nil
	file_cav_proto_goTypes = nil
	file_cav_proto_depIdxs = nil
}
